# Generated by Django 5.2.1 on 2025-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='location',
        ),
        migrations.AddField(
            model_name='freight',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freight',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freight',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freight',
            name='origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
